-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2021-06-21 23:39:09.043

-- tables
-- Table: GANADOR
CREATE TABLE GANADOR (
    IDGAN serial  NOT NULL,
    IDPER int  NOT NULL,
    IDPRE int  NOT NULL,
    CONSTRAINT GANADOR_pk PRIMARY KEY (IDGAN)
);

-- Table: PERSONA
CREATE TABLE PERSONA (
    IDPER serial  NOT NULL,
    NOMPER varchar(30)  NOT NULL,
    NUMPER int  NOT NULL,
    ESTPER char(1)  NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY (IDPER)
);

-- Table: PREMIO
CREATE TABLE PREMIO (
    IDPRE serial  NOT NULL,
    NOMPRE varchar(30)  NOT NULL,
    DESPRE varchar(50)  NOT NULL,
    ESTPRE char(1)  NOT NULL,
    ORDPRE int  NOT NULL,
    CONSTRAINT PREMIO_pk PRIMARY KEY (IDPRE)
);

-- foreign keys
-- Reference: GANADOR_PERSONA (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_PERSONA
    FOREIGN KEY (IDPER)
    REFERENCES PERSONA (IDPER)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: GANADOR_PREMIO (table: GANADOR)
ALTER TABLE GANADOR ADD CONSTRAINT GANADOR_PREMIO
    FOREIGN KEY (IDPRE)
    REFERENCES PREMIO (IDPRE)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- End of file.

